name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        java: ["8", "11"]
        arch:
          - 'x86_64'
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}        
      - name: Install Dependencies
        run: |
         sudo apt-get update -y && sudo apt-get install openjdk-8-jdk -y 
         export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
         export PATH=$PATH:$JAVA_HOME/bin
         echo $PATH
         mvn spring-boot:run
        
  test_arm64: 
     runs-on: ubuntu-latest
     strategy:
      matrix:
        java: ["8"]
      fail-fast: false
     steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Install and Run tests
        run: |
               docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
               arm64v8/ubuntu:20.04 \
               bash -exc 'apt-get update -y && \
               apt-get install openjdk-8-jdk -y && \
               export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-arm64 && \
               export PATH=$PATH:$JAVA_HOME/bin && \
               echo $PATH && \
               apt-get install maven -y && \
               mvn clean install && \
               mvn spring-boot:run'
